// apps/angular-admin/src/app/auth/login/login-captcha.ts
import {
  AfterViewInit,
  Component,
  ElementRef,
  Injector,
  OnDestroy,
  afterNextRender,
  computed,
  inject,
  input,
  output,
  viewChild,
} from '@angular/core';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { LOGIN_MESSAGES } from '../auth.messages';
import { loadTurnstileWidget, type TurnstileWidgetApi } from '../turnstile-loader';

/**
 * Presentational login captcha (KYC-094).
 * Turnstile widget when a site key is set; otherwise a labeled token field (API `test` provider).
 */
@Component({
  selector: 'app-login-captcha',
  imports: [MatFormFieldModule, MatInputModule],
  templateUrl: './login-captcha.html',
  styleUrl: './login-captcha.css',
})
export class LoginCaptcha implements AfterViewInit, OnDestroy {
  readonly siteKey = input<string>('');
  readonly disabled = input<boolean>(false);
  readonly invalid = input<boolean>(false);
  readonly tokenChange = output<string>();
  readonly loadFailed = output<void>();

  protected readonly copy: typeof LOGIN_MESSAGES = LOGIN_MESSAGES;
  protected readonly usesWidget = computed((): boolean => this.siteKey().trim().length > 0);
  private readonly injector: Injector = inject(Injector);
  private readonly widgetHost = viewChild<ElementRef<HTMLDivElement>>('widgetHost');

  private widgetApi: TurnstileWidgetApi | null = null;
  private widgetId: string | null = null;
  private destroyed: boolean = false;

  ngAfterViewInit(): void {
    afterNextRender(
      (): void => {
        const siteKey: string = this.siteKey().trim();
        if (!siteKey) {
          return;
        }
        void this.mountWidget(siteKey);
      },
      { injector: this.injector },
    );
  }

  ngOnDestroy(): void {
    this.destroyed = true;
    this.removeWidget();
  }

  resetWidget(): void {
    if (this.widgetApi && this.widgetId) {
      this.widgetApi.reset(this.widgetId);
    }
    this.tokenChange.emit('');
  }

  protected onTokenInput(event: Event): void {
    const target: EventTarget | null = event.target;
    if (!(target instanceof HTMLInputElement)) {
      return;
    }
    this.tokenChange.emit(target.value);
  }

  private async mountWidget(siteKey: string): Promise<void> {
    try {
      const api: TurnstileWidgetApi = await loadTurnstileWidget();
      if (this.destroyed) {
        return;
      }
      const host: HTMLDivElement | undefined = this.widgetHost()?.nativeElement;
      if (!host) {
        this.loadFailed.emit();
        return;
      }
      this.widgetApi = api;
      this.widgetId = api.render(host, {
        sitekey: siteKey,
        callback: (token: string): void => {
          this.tokenChange.emit(token);
        },
        'expired-callback': (): void => {
          this.tokenChange.emit('');
        },
        'error-callback': (): void => {
          this.tokenChange.emit('');
        },
        theme: 'auto',
      });
    } catch {
      if (!this.destroyed) {
        this.loadFailed.emit();
      }
    }
  }

  private removeWidget(): void {
    if (this.widgetApi && this.widgetId) {
      this.widgetApi.remove(this.widgetId);
    }
    this.widgetApi = null;
    this.widgetId = null;
  }
}

// apps/react-customer/src/auth/login-page/login-captcha.tsx
import {
  type ChangeEvent,
  type ReactElement,
  forwardRef,
  useEffect,
  useImperativeHandle,
  useRef,
} from 'react';
import { LOGIN_MESSAGES, type LoginMessages } from '../auth.messages';
import { loadTurnstileWidget, type TurnstileWidgetApi } from '../turnstile-loader';
import styles from './login-captcha.module.css';

export interface LoginCaptchaHandle {
  reset: () => void;
}

export interface LoginCaptchaProps {
  readonly siteKey: string;
  readonly disabled: boolean;
  readonly invalid: boolean;
  readonly value: string;
  readonly onTokenChange: (token: string) => void;
  readonly onLoadFailed: () => void;
}

/**
 * Presentational login captcha (KYC-094).
 * Turnstile widget when a site key is set; otherwise a labeled token field (API `test` provider).
 */
export const LoginCaptcha = forwardRef<LoginCaptchaHandle, LoginCaptchaProps>(
  function LoginCaptcha(
    { siteKey, disabled, invalid, value, onTokenChange, onLoadFailed }: LoginCaptchaProps,
    ref,
  ): ReactElement {
    const copy: LoginMessages = LOGIN_MESSAGES;
    const usesWidget: boolean = siteKey.trim().length > 0;
    const hostRef = useRef<HTMLDivElement | null>(null);
    const apiRef = useRef<TurnstileWidgetApi | null>(null);
    const widgetIdRef = useRef<string | null>(null);
    const onTokenChangeRef = useRef(onTokenChange);
    const onLoadFailedRef = useRef(onLoadFailed);

    useEffect((): void => {
      onTokenChangeRef.current = onTokenChange;
      onLoadFailedRef.current = onLoadFailed;
    });

    useImperativeHandle(ref, (): LoginCaptchaHandle => {
      return {
        reset: (): void => {
          if (apiRef.current && widgetIdRef.current) {
            apiRef.current.reset(widgetIdRef.current);
          }
          onTokenChangeRef.current('');
        },
      };
    }, []);

    useEffect((): (() => void) | void => {
      if (!usesWidget) {
        return;
      }
      let cancelled: boolean = false;
      const site: string = siteKey.trim();
      void loadTurnstileWidget()
        .then((api: TurnstileWidgetApi): void => {
          if (cancelled) {
            return;
          }
          const host: HTMLDivElement | null = hostRef.current;
          if (!host) {
            onLoadFailedRef.current();
            return;
          }
          apiRef.current = api;
          widgetIdRef.current = api.render(host, {
            sitekey: site,
            callback: (token: string): void => {
              onTokenChangeRef.current(token);
            },
            'expired-callback': (): void => {
              onTokenChangeRef.current('');
            },
            'error-callback': (): void => {
              onTokenChangeRef.current('');
            },
            theme: 'auto',
          });
        })
        .catch((): void => {
          if (!cancelled) {
            onLoadFailedRef.current();
          }
        });

      return (): void => {
        cancelled = true;
        if (apiRef.current && widgetIdRef.current) {
          apiRef.current.remove(widgetIdRef.current);
        }
        apiRef.current = null;
        widgetIdRef.current = null;
      };
    }, [usesWidget, siteKey]);

    if (usesWidget) {
      return (
        <div className={styles['captcha']}>
          <p className={styles['label']} id="login-captcha-label">
            {copy.captchaLabel}
          </p>
          <div
            ref={hostRef}
            className={styles['widget']}
            role="group"
            aria-labelledby="login-captcha-label"
            aria-invalid={invalid || undefined}
            aria-describedby={invalid ? 'captcha-error' : undefined}
          />
          {invalid ? (
            <p id="captcha-error" className={styles['error']}>
              {copy.captchaRequired}
            </p>
          ) : null}
        </div>
      );
    }

    return (
      <div className={styles['captcha']}>
        <label htmlFor="captchaToken">{copy.captchaLabel}</label>
        <input
          id="captchaToken"
          name="captchaToken"
          type="text"
          autoComplete="off"
          spellCheck={false}
          maxLength={2048}
          disabled={disabled}
          value={value}
          onChange={(event: ChangeEvent<HTMLInputElement>): void => {
            onTokenChange(event.target.value);
          }}
          aria-invalid={invalid}
          aria-describedby={invalid ? 'captcha-error' : 'captcha-help'}
        />
        <p id="captcha-help" className={styles['help']}>
          {copy.captchaHelp}
        </p>
        {invalid ? (
          <p id="captcha-error" className={styles['error']}>
            {copy.captchaRequired}
          </p>
        ) : null}
      </div>
    );
  },
);
